In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

In [3]:
df = pd.read_csv("F:\\Dataset\\Advertising.csv")

In [4]:
df.head()

,Unnamed: 0,TV,Radio,Newspaper,Sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9


In [5]:
df = df.iloc[:,1:]

In [7]:
df.head()

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [8]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [11]:
df.describe()

,TV,Radio,Newspaper,Sales
count,200.000000,200.000000,200.000000,200.000000
mean,147.042500,23.264000,30.554000,14.022500
std,85.854236,14.846809,21.778621,5.217457
min,0.700000,0.000000,0.300000,1.600000
25%,74.375000,9.975000,12.750000,10.375000
50%,149.750000,22.900000,25.750000,12.900000
75%,218.825000,36.525000,45.100000,17.400000
max,296.400000,49.600000,114.000000,27.000000


In [12]:
df.corr()

,TV,Radio,Newspaper,Sales
TV,1.000000,0.054809,0.056648,0.782224
Radio,0.054809,1.000000,0.354104,0.576223
Newspaper,0.056648,0.354104,1.000000,0.228299
Sales,0.782224,0.576223,0.228299,1.000000


In [13]:
X = df.drop("Sales", axis=1)

In [14]:
X.shape

(200, 3)

In [15]:
y = df.Sales

In [16]:
y.shape

(200,)

In [17]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [18]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape 

((160, 3), (40, 3), (160,), (40,))

In [19]:
scl = StandardScaler()

In [20]:
x_train_scaled = scl.fit_transform(x_train)

In [21]:
x_test_scaled = scl.transform(x_test)

In [22]:
lr = LinearRegression()

In [23]:
lr.fit(x_train_scaled, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [24]:
lr.intercept_

13.87125

In [25]:
lr.coef_

array([ 4.07686894,  2.76432822, -0.10958854])

In [27]:
y_pred = lr.predict(x_test_scaled)

In [28]:
pd.DataFrame({"y_true": y_test, "y_pred": y_pred})

,y_true,y_pred
45,14.9,15.188873
72,8.8,10.205411
40,16.6,16.439320
58,23.8,21.808189
25,12.0,15.887521
13,9.7,8.926802
153,19.0,18.135673
80,11.8,11.365894
3,18.5,17.397555
44,8.5,8.669504


In [29]:
mean_squared_error(y_test, y_pred)

2.2564942472809344

In [30]:
mean_absolute_error(y_test, y_pred)

1.0788802763848646

In [31]:
r2_score(y_test, y_pred)

0.8955882331233613

In [39]:
l1 = Lasso(alpha=0.1)

In [40]:
l1.fit(x_train_scaled, y_train)

,alpha,0.1
,fit_intercept,True
,precompute,False
,copy_X,True
,max_iter,1000
,tol,0.0001
,warm_start,False
,positive,False
,random_state,None
,selection,'cyclic'


In [41]:
l1.intercept_

13.87125

In [42]:
l1.coef_

array([ 3.97459016,  2.62933716, -0.        ])

In [43]:
y_pred_l1 = l1.predict(x_test_scaled)

In [44]:
mean_squared_error(y_test, y_pred_l1)

2.2117440472033407

In [45]:
r2_score(y_test, y_pred)

0.8955882331233613

In [46]:
joblib.dump(lr, "linear.pkl")

['linear.pkl']

In [47]:
joblib.dump(scl, "scaler.pkl")

['scaler.pkl']

In [48]:
new_data = [[220,35, 65]]

In [49]:
LR = joblib.load("linear.pkl")

In [50]:
Scl = joblib.load("scaler.pkl")

In [52]:
new_record = Scl.transform(new_data)

C:\Users\amitm\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [53]:
LR.predict(new_record)

array([19.42919148])